Removed partial jquery dep
Presto412/CryptoFS pull request #14
Opened 2020-10-10 13:52 UTC by dshubhadeep

Removed query dep. in all files except  [list.js](https://github.com/Presto412/CryptoFS/blob/master/src/public/js/list.js).

2020-10-11 04:11 UTC, chris--jones commented
Why not list.js?

2020-10-11 04:15 UTC, chris--jones commented on src/public/js/util.js
> +    el.style.display = 'block';
This is not ideal as not all elements may be block-level, instead set the display style property to an empty string.

2020-10-11 05:04 UTC, dshubhadeep commented
> Why not list.js?

I had to confirm with @Presto412 on how to replace the ajax function. I'll make the changes shortly.

2020-10-11 05:24 UTC, chris--jones commented
> 
> 
> > Why not list.js?
> 
> I had to confirm with @Presto412 on how to replace the ajax function. I'll make the changes shortly.

You can use fetch (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)
I have used similar in my PR for file encryption #15

2020-10-12 18:34 UTC, Presto412 commented
@dshubhadeep just merged some changes related to file encryption, could you please resolve conflicts and run 
```sh
npx webpack  --mode=production
```
Thanks

2020-10-12 18:56 UTC, dshubhadeep commented
> @dshubhadeep just merged some changes related to file encryption, could you please resolve conflicts and run
> 
> ```shell
> npx webpack  --mode=production
> ```
> 
> Thanks

Done. Please check once

2020-10-12 19:06 UTC, Presto412 commented
@dshubhadeep Doesn't seem to work, not able to expand Login tab and no message shown in the files tab as well. Please check

2020-10-13 12:12 UTC, chris--jones requested changes

2020-10-13 17:36 UTC, Presto412 approved these changes

2020-10-13 17:36 UTC, merged